# Generated by Django 5.2.5 on 2025-08-14 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("patient_name", models.CharField(db_index=True, max_length=255)),
                ("billed_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Denied", "Denied"),
                            ("Under Review", "Under Review"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("insurer_name", models.CharField(db_index=True, max_length=255)),
                ("discharge_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ClaimDetail",
            fields=[
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="details",
                        serialize=False,
                        to="claims.claim",
                    ),
                ),
                ("denial_reason", models.TextField(blank=True, null=True)),
                ("cpt_codes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
