# Generated by Django 5.2.5 on 2025-09-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimdetail",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
